name: Create and publish master image

on:
  push:
    branches:
      - master
      - feat_push_image_master_to_sbx

jobs:
  CreateAndPublish:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install all the build and lint dependencies
        run: make setup
        
      - name: Install dependency
        run: |
          sudo apt-get update
          sudo apt install -y httpie
          sudo apt install -y protobuf-compiler

      - name: Get submodule
        run: |
          sed -i 's,git\@github.com:\([^/]*\)/\(.*\).git,https://github.com/\1/\2,' .gitmodules
          git submodule update --init --recursive

      - name: Build a version
        run: make build
        
      - name: Run all the tests
        run: make test

      - name: create publish release images
        run: |
          make docker
          make dockerhub-login DOCKERHUB_USER=${{secrets.DOCKERHUB_USER}} DOCKERHUB_PWD=${{secrets.DOCKERHUB_PWD}}
          make push-image-forseti-master

      - name: Publish master images to aws:sbx
        run: |
          make push-image-forseti-master-to-sbx

      - name: slack notification (the job has failed)
        if: failure()
        run: |
          echo '{"text":":warning: Forseti Github Actions: Create image for branch master failed ! (https://github.com/hove-io/forseti/actions/workflows/master.yml)."}' | http --json POST ${{secrets.SLACK_NAVITIA_CORE_TEAM_URL}}

  PushImageAws:
    if: github.event_name == 'push'
    needs: CreateAndPublish
    runs-on: [ self-hosted, forseti, sandbox ]
    steps:
      - name: Push dev images to aws sandbox registry
        if: github.event_name == 'push'
        run: make push-image-forseti-master-to-sbx
