name: Create and publish release image

on:
  push:
    tags:
      - '*'

jobs:

  CreateAndPublish:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Install all the build and lint dependencies
        run: make setup

      - name: Install dependency
        run: |
          sudo apt-get update
          sudo apt install -y httpie
          sudo apt install -y protobuf-compiler
      
      - name: Get submodule
        run: |
          sed -i 's,git\@github.com:\([^/]*\)/\(.*\).git,https://github.com/\1/\2,' .gitmodules
          git submodule update --init --recursive

      - name: Build a version
        run: make build
      
      - name: Run all the tests
        run: make test    

      - name: create publish release images
        run: |
          make docker
          make dockerhub-login DOCKERHUB_USER=${{secrets.DOCKERHUB_USER}} DOCKERHUB_PWD=${{secrets.DOCKERHUB_PWD}}
          make push-image-forseti-release

      - name: Github Release
        uses: softprops/action-gh-release@v1
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: slack notification (the job has failed)
        if: failure()
        run: |
          echo '{"text":":warning: Forseti Github Actions: Create image for branch realse failed ! (https://github.com/hove-io/forseti/actions/workflows/release.yml)."}' | http --json POST ${{secrets.SLACK_NAVITIA_CORE_TEAM_URL}}

      - name: trig publishing + notifications (the job has successed)
        if: success()
        run: |
          VERSION=$(git tag -l --sort=-v:refname| sed 's/v//g'| head -n 1)
          echo '{"text":":information_source: Forseti Github Actions: Create image for branch realse succeded - New image forseti' $VERSION 'is available"}' | http --json POST ${{secrets.SLACK_NAVITIA_CORE_TEAM_URL}}
